apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-route-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: route-api
  template:
    metadata:
      name: nest-route-api
      labels:
        app.kubernetes.io/name: route-api
    spec:
      containers:
        - name: nest-route-api
          image: jmsstudio/fsfc2-nest-route-api
          ports:
            - containerPort: 3000
